"""empty message

Revision ID: 422a942c26d8
Revises: a9402fcb2ec5
Create Date: 2018-07-19 03:19:40.865281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422a942c26d8'
down_revision = 'a9402fcb2ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
